[package]
name = "kvs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
log = {version = "0.4", features = ["std"]}
simple_logger = "5.0"
nix = {version="0.29.0", features = ["fs"]}


 [lib]

 [dev-dependencies]
 tempfile = "3.16"
 test = "0.1"
