name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Style
      run: cargo fmt
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  example:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Style
      run: cargo fmt
    - name: Build example
      run: cargo build --example example
    - name: Run example
      run: |
        sudo apt-get update
        sudo apt-get install -y strace
        strace -c -S calls -o output.txt cargo run --example example
        cat output.txt

    # - name: Upload strace output as artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: output
    #     path: output.txt

  miri:
    name: "Miri"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Test with Miri
        run: cargo miri test
      - name: Example with Miri
        run: cargo run --example example
