name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v4
    - name: Show rustc version and platform
      run: |
        rustc --version --verbose
    - name: Style
      run: cargo fmt
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  example:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Style
      run: cargo fmt
    - name: Build example
      run: cargo build --example example -r
    - name: Run example
      run: |
        sudo apt-get update
        sudo apt-get install -y strace
        strace -c -S calls -o output.txt cargo run --example example
        cat output.txt

  bench:

    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v4

      - name: Run bench
        run: cargo bench --release
